image: python:3.7.2
pipelines:
  default:
    - step:
        script:
          - pip install -r requirements.txt
          - pycodestyle --exclude='venv,dealenv,dealenv2' .
          - pytest test.py
          