image: python:3.7.2
pipelines:
  default:
    - step:
        script:
          - pip install -r backend/app/requirements.txt
          - python backend/app/test.py
          - pycodestyle --exclude='venv,dealenv,dealenv2' --ignore E501 .
