image: python:3.7.2
pipelines:
  default:
    - step:
        script:
          - pip install -r requirements.txt
          - pytest test.py
          - python
          - pycodestyle --exclude='venv,dealenv,dealenv2' --ignore E501 .
          