version: "3.7"
services:
  docker-fastapi:
    container_name: docker-fastapi
    build:
      context: ./app/
      dockerfile: Dockerfile
    restart: always
  nginx:
    depends_on:
      - docker-fastapi
    container_name: proxy-app
    build:
      context: ./ui/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
