version: "3.7"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 1337:80
  backend:
    container_name: backend
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    ports:
      - 8000:80
