version: "3.7"
services:
  frontend:
    container_name: frontend
    image: dealtale.azurecr.io/fatdealapife
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 1337:80
  backend:
    container_name: backend
    image: dealtale.azurecr.io/fatdealapi
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    ports:
      - 8000:80
